import type { QuestionDefinition } from "@/types";

// Single source of truth for the full questionnaire.
// Pages render from this config — no hardcoded question text in JSX.

export const STEP_TITLES: Record<1 | 2 | 3 | 4 | 5, string> = {
  1: "הגדרת הרעיון",
  2: "פרופיל מייסד",
  3: "בעיה ושוק",
  4: "מוניטיזציה, תחרות והפצה",
  5: "ביצוע וסיכון",
};

export const STEP_DESCRIPTIONS: Record<1 | 2 | 3 | 4 | 5, string> = {
  1: "נגדיר במדויק מה אתה בונה, למי, ולמה.",
  2: "נבחן את ההתאמה שלך כמייסד לרעיון הזה.",
  3: "נבדוק עד כמה הבעיה אמיתית והשוק קיים.",
  4: "נבחן איך תרוויח, מול מי תתחרה ואיך תגיע ללקוחות.",
  5: "נבחן את הסיכון הקריטי ואת מה שצריך לאמת קודם.",
};

export const QUESTIONS: QuestionDefinition[] = [
  // ─── Step 1 — Idea Definition ─────────────────────────────
  {
    key: "idea_name",
    step: 1,
    section: "problem",
    type: "short_text",
    label: "מה שם הרעיון?",
    helper_text: "שם עבודה — אפשר לשנות בהמשך.",
    placeholder: "לדוגמה: ClearBrief",
    required: true,
  },
  {
    key: "idea_description",
    step: 1,
    section: "problem",
    type: "long_text",
    label: "תאר את הרעיון ב־2–5 משפטים",
    helper_text: "תיאור קצר וברור. מה זה, למי, ולמה.",
    placeholder: "מערכת ש…",
    required: true,
    ai_classification_needed: true,
  },
  {
    key: "first_customer",
    step: 1,
    section: "market",
    type: "long_text",
    label: "מי הלקוח הראשון שאתה רוצה למכור לו?",
    helper_text: "תפקיד, גודל ארגון, ענף — ככל שיותר ספציפי יותר טוב.",
    required: true,
  },
  {
    key: "core_problem",
    step: 1,
    section: "problem",
    type: "long_text",
    label: "מה הבעיה המרכזית שאתה פותר?",
    helper_text: "תאר את הבעיה במילים של הלקוח, לא במונחי הפתרון.",
    required: true,
    ai_classification_needed: true,
  },
  {
    key: "current_solution",
    step: 1,
    section: "differentiation",
    type: "long_text",
    label: "איך פותרים את זה היום?",
    helper_text: "כלים, תהליכים ידניים, או חוסר פתרון.",
    required: true,
  },
  {
    key: "differentiator",
    step: 1,
    section: "differentiation",
    type: "long_text",
    label: "מה שונה בפתרון שלך?",
    helper_text: "במה אתה שונה ממה שקיים — לא טוב יותר, שונה.",
    required: true,
    ai_classification_needed: true,
  },
  {
    key: "revenue_model",
    step: 1,
    section: "monetization",
    type: "long_text",
    label: "איך העסק ירוויח כסף?",
    helper_text: "מודל הכנסה ראשוני — מי משלם ועל מה.",
    required: true,
  },

  // ─── Step 2 — Founder Profile ─────────────────────────────
  {
    key: "founder_domain_experience",
    step: 2,
    section: "founder_fit",
    type: "single_choice",
    label: "מה רמת הניסיון שלך בתחום?",
    required: true,
    options: [
      { value: "none", label: "אין ניסיון" },
      { value: "some", label: "ניסיון חלקי" },
      { value: "deep", label: "ניסיון עמוק" },
      { value: "expert", label: "מומחה בתחום" },
    ],
  },
  {
    key: "founder_sales_skill",
    step: 2,
    section: "founder_fit",
    type: "single_choice",
    label: "מה רמת היכולת שלך במכירה?",
    required: true,
    options: [
      { value: "low", label: "נמוכה" },
      { value: "medium", label: "בינונית" },
      { value: "high", label: "גבוהה" },
      { value: "expert", label: "מקצועית" },
    ],
  },
  {
    key: "founder_build_skill",
    step: 2,
    section: "founder_fit",
    type: "single_choice",
    label: "מה רמת היכולת שלך לבנות או להוביל מוצר?",
    required: true,
    options: [
      { value: "low", label: "נמוכה" },
      { value: "medium", label: "בינונית" },
      { value: "high", label: "גבוהה" },
      { value: "expert", label: "מקצועית" },
    ],
  },
  {
    key: "founder_weekly_hours",
    step: 2,
    section: "founder_fit",
    type: "single_choice",
    label: "כמה זמן תוכל להשקיע בזה בשבוע?",
    required: true,
    options: [
      { value: "lt5", label: "פחות מ־5 שעות" },
      { value: "5_15", label: "5–15 שעות" },
      { value: "15_30", label: "15–30 שעות" },
      { value: "ft", label: "במשרה מלאה" },
    ],
  },
  {
    key: "founder_assets",
    step: 2,
    section: "founder_fit",
    type: "multi_choice",
    label: "אילו נכסים כבר יש לך?",
    helper_text: "סמן את כל מה שרלוונטי.",
    options: [
      { value: "audience", label: "קהל / רשת מקצועית" },
      { value: "domain", label: "מומחיות בתחום" },
      { value: "capital", label: "הון עצמי" },
      { value: "team", label: "צוות" },
      { value: "tech", label: "יכולת טכנית" },
      { value: "distribution", label: "ערוץ הפצה" },
    ],
  },
  {
    key: "founder_unfair_advantage",
    step: 2,
    section: "founder_fit",
    type: "long_text",
    label: "איזה יתרון יש לך על פני מישהו אחר שיבנה את אותו רעיון?",
    helper_text: "יתרון אמיתי, לא מאמץ.",
    required: true,
    ai_classification_needed: true,
  },

  // ─── Step 3 — Problem and Market ─────────────────────────
  {
    key: "problem_intensity",
    step: 3,
    section: "problem",
    type: "single_choice",
    label: "עד כמה הבעיה כואבת?",
    required: true,
    options: [
      { value: "1", label: "מטרד קטן" },
      { value: "2", label: "מציק" },
      { value: "3", label: "כואב" },
      { value: "4", label: "כואב מאוד" },
      { value: "5", label: "בלתי נסבל" },
    ],
  },
  {
    key: "problem_frequency",
    step: 3,
    section: "problem",
    type: "single_choice",
    label: "באיזו תדירות היא מתרחשת?",
    required: true,
    options: [
      { value: "rare", label: "לעיתים נדירות" },
      { value: "monthly", label: "חודשי" },
      { value: "weekly", label: "שבועי" },
      { value: "daily", label: "יומי" },
      { value: "constant", label: "כל הזמן" },
    ],
  },
  {
    key: "problem_consequence",
    step: 3,
    section: "problem",
    type: "long_text",
    label: "מה קורה אם לא פותרים אותה?",
    helper_text: "השלכה ממשית — כסף, זמן, סיכון, מוניטין.",
    required: true,
  },
  {
    key: "existing_payment",
    step: 3,
    section: "market",
    type: "single_choice",
    label: "האם הלקוחות כבר משלמים על משהו דומה או קרוב?",
    required: true,
    options: [
      { value: "no", label: "לא" },
      { value: "indirect", label: "עקיף — פתרון משיק" },
      { value: "yes_low", label: "כן, סכומים נמוכים" },
      { value: "yes_high", label: "כן, סכומים משמעותיים" },
    ],
  },
  {
    key: "market_size_estimate",
    step: 3,
    section: "market",
    type: "long_text",
    label: "כמה לקוחות כאלה יש בשוק הראשוני שלך?",
    helper_text: "אומדן גס מספיק. ציין את המקור אם יש.",
    required: true,
  },
  {
    key: "trigger_moment",
    step: 3,
    section: "market",
    type: "long_text",
    label: "האם יש רגע ברור שבו הם מחפשים פתרון?",
    helper_text: "אירוע, שינוי, רגולציה, גיוס — מה הטריגר.",
    required: true,
  },

  // ─── Step 4 — Monetization, Competition, Distribution ────
  {
    key: "price_point",
    step: 4,
    section: "monetization",
    type: "short_text",
    label: "כמה אפשר לגבות?",
    helper_text: "מחיר ראשוני בכל יחידה (חודש / שימוש / רישיון).",
    required: true,
  },
  {
    key: "pricing_model",
    step: 4,
    section: "monetization",
    type: "single_choice",
    label: "מה מודל התמחור?",
    required: true,
    options: [
      { value: "subscription", label: "מנוי חודשי / שנתי" },
      { value: "usage", label: "תשלום לפי שימוש" },
      { value: "license", label: "רישיון חד פעמי" },
      { value: "service", label: "שירות / פרויקט" },
      { value: "marketplace", label: "מרקטפלייס / עמלה" },
      { value: "other", label: "אחר" },
    ],
  },
  {
    key: "direct_competitors",
    step: 4,
    section: "differentiation",
    type: "long_text",
    label: "האם יש מתחרים ישירים?",
    helper_text: "מי הם, ובמה הם חזקים.",
    required: true,
  },
  {
    key: "why_buy_from_you",
    step: 4,
    section: "differentiation",
    type: "long_text",
    label: "למה שלקוחות יקנו דווקא ממך?",
    helper_text: "סיבה חדה אחת לפחות.",
    required: true,
    ai_classification_needed: true,
  },
  {
    key: "first_10_customers",
    step: 4,
    section: "distribution",
    type: "long_text",
    label: "איך תשיג את 10 הלקוחות הראשונים?",
    helper_text: "פעולות קונקרטיות, לא ערוצים כלליים.",
    required: true,
  },
  {
    key: "first_100_customers",
    step: 4,
    section: "distribution",
    type: "long_text",
    label: "איך תשיג את 100 הלקוחות הראשונים?",
    helper_text: "ערוץ אחד או שניים שעובדים בקנה מידה.",
    required: true,
  },
  {
    key: "ease_of_copy",
    step: 4,
    section: "differentiation",
    type: "single_choice",
    label: "עד כמה קל להעתיק את הרעיון?",
    required: true,
    options: [
      { value: "trivial", label: "קל מאוד" },
      { value: "easy", label: "קל" },
      { value: "moderate", label: "בינוני" },
      { value: "hard", label: "קשה" },
      { value: "very_hard", label: "קשה מאוד" },
    ],
  },

  // ─── Step 5 — Execution and Risk ─────────────────────────
  {
    key: "first_payment_requirements",
    step: 5,
    section: "execution",
    type: "long_text",
    label: "מה חייב להתקיים כדי שלקוח ראשון ישלם?",
    helper_text: "תנאים מינימליים — לא מוצר מלא.",
    required: true,
  },
  {
    key: "manual_first_version",
    step: 5,
    section: "execution",
    type: "long_text",
    label: "מה אפשר לעשות ידנית לפני שבונים מערכת?",
    helper_text: "Concierge / שירות ידני / אקסל.",
    required: true,
  },
  {
    key: "riskiest_assumption",
    step: 5,
    section: "execution",
    type: "long_text",
    label: "מה ההנחה הכי מסוכנת?",
    helper_text: "ההנחה שאם תתבדה — הכל קורס.",
    required: true,
    ai_classification_needed: true,
  },
  {
    key: "first_14_days_test",
    step: 5,
    section: "execution",
    type: "long_text",
    label: "אם היו לך 14 יום, מה היית בודק קודם?",
    helper_text: "פעולה אחת קונקרטית עם תוצאה מדידה.",
    required: true,
  },
  {
    key: "regulatory_risk",
    step: 5,
    section: "execution",
    type: "long_text",
    label: "האם יש סיכון משפטי, רגולטורי או תפעולי חריג?",
    helper_text: "אם אין — כתוב 'אין'. אם יש — תאר בקצרה.",
    required: true,
  },
];

export const QUESTIONS_BY_STEP = QUESTIONS.reduce<
  Record<1 | 2 | 3 | 4 | 5, QuestionDefinition[]>
>(
  (acc, q) => {
    acc[q.step].push(q);
    return acc;
  },
  { 1: [], 2: [], 3: [], 4: [], 5: [] },
);

export const TOTAL_STEPS = 5 as const;
