/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportIdeaIdRouteImport } from './routes/report.$ideaId'
import { Route as IdeaNewRouteImport } from './routes/idea.new'
import { Route as ReportIdeaIdPrintRouteImport } from './routes/report.$ideaId.print'
import { Route as IdeaIdeaIdStep5RouteImport } from './routes/idea.$ideaId.step-5'
import { Route as IdeaIdeaIdStep4RouteImport } from './routes/idea.$ideaId.step-4'
import { Route as IdeaIdeaIdStep3RouteImport } from './routes/idea.$ideaId.step-3'
import { Route as IdeaIdeaIdStep2RouteImport } from './routes/idea.$ideaId.step-2'
import { Route as IdeaIdeaIdStep1RouteImport } from './routes/idea.$ideaId.step-1'
import { Route as IdeaIdeaIdAnalyzingRouteImport } from './routes/idea.$ideaId.analyzing'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIdeaIdRoute = ReportIdeaIdRouteImport.update({
  id: '/report/$ideaId',
  path: '/report/$ideaId',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeaNewRoute = IdeaNewRouteImport.update({
  id: '/idea/new',
  path: '/idea/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIdeaIdPrintRoute = ReportIdeaIdPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => ReportIdeaIdRoute,
} as any)
const IdeaIdeaIdStep5Route = IdeaIdeaIdStep5RouteImport.update({
  id: '/idea/$ideaId/step-5',
  path: '/idea/$ideaId/step-5',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeaIdeaIdStep4Route = IdeaIdeaIdStep4RouteImport.update({
  id: '/idea/$ideaId/step-4',
  path: '/idea/$ideaId/step-4',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeaIdeaIdStep3Route = IdeaIdeaIdStep3RouteImport.update({
  id: '/idea/$ideaId/step-3',
  path: '/idea/$ideaId/step-3',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeaIdeaIdStep2Route = IdeaIdeaIdStep2RouteImport.update({
  id: '/idea/$ideaId/step-2',
  path: '/idea/$ideaId/step-2',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeaIdeaIdStep1Route = IdeaIdeaIdStep1RouteImport.update({
  id: '/idea/$ideaId/step-1',
  path: '/idea/$ideaId/step-1',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeaIdeaIdAnalyzingRoute = IdeaIdeaIdAnalyzingRouteImport.update({
  id: '/idea/$ideaId/analyzing',
  path: '/idea/$ideaId/analyzing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/idea/new': typeof IdeaNewRoute
  '/report/$ideaId': typeof ReportIdeaIdRouteWithChildren
  '/idea/$ideaId/analyzing': typeof IdeaIdeaIdAnalyzingRoute
  '/idea/$ideaId/step-1': typeof IdeaIdeaIdStep1Route
  '/idea/$ideaId/step-2': typeof IdeaIdeaIdStep2Route
  '/idea/$ideaId/step-3': typeof IdeaIdeaIdStep3Route
  '/idea/$ideaId/step-4': typeof IdeaIdeaIdStep4Route
  '/idea/$ideaId/step-5': typeof IdeaIdeaIdStep5Route
  '/report/$ideaId/print': typeof ReportIdeaIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/idea/new': typeof IdeaNewRoute
  '/report/$ideaId': typeof ReportIdeaIdRouteWithChildren
  '/idea/$ideaId/analyzing': typeof IdeaIdeaIdAnalyzingRoute
  '/idea/$ideaId/step-1': typeof IdeaIdeaIdStep1Route
  '/idea/$ideaId/step-2': typeof IdeaIdeaIdStep2Route
  '/idea/$ideaId/step-3': typeof IdeaIdeaIdStep3Route
  '/idea/$ideaId/step-4': typeof IdeaIdeaIdStep4Route
  '/idea/$ideaId/step-5': typeof IdeaIdeaIdStep5Route
  '/report/$ideaId/print': typeof ReportIdeaIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/idea/new': typeof IdeaNewRoute
  '/report/$ideaId': typeof ReportIdeaIdRouteWithChildren
  '/idea/$ideaId/analyzing': typeof IdeaIdeaIdAnalyzingRoute
  '/idea/$ideaId/step-1': typeof IdeaIdeaIdStep1Route
  '/idea/$ideaId/step-2': typeof IdeaIdeaIdStep2Route
  '/idea/$ideaId/step-3': typeof IdeaIdeaIdStep3Route
  '/idea/$ideaId/step-4': typeof IdeaIdeaIdStep4Route
  '/idea/$ideaId/step-5': typeof IdeaIdeaIdStep5Route
  '/report/$ideaId/print': typeof ReportIdeaIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/idea/new'
    | '/report/$ideaId'
    | '/idea/$ideaId/analyzing'
    | '/idea/$ideaId/step-1'
    | '/idea/$ideaId/step-2'
    | '/idea/$ideaId/step-3'
    | '/idea/$ideaId/step-4'
    | '/idea/$ideaId/step-5'
    | '/report/$ideaId/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/idea/new'
    | '/report/$ideaId'
    | '/idea/$ideaId/analyzing'
    | '/idea/$ideaId/step-1'
    | '/idea/$ideaId/step-2'
    | '/idea/$ideaId/step-3'
    | '/idea/$ideaId/step-4'
    | '/idea/$ideaId/step-5'
    | '/report/$ideaId/print'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/idea/new'
    | '/report/$ideaId'
    | '/idea/$ideaId/analyzing'
    | '/idea/$ideaId/step-1'
    | '/idea/$ideaId/step-2'
    | '/idea/$ideaId/step-3'
    | '/idea/$ideaId/step-4'
    | '/idea/$ideaId/step-5'
    | '/report/$ideaId/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  IdeaNewRoute: typeof IdeaNewRoute
  ReportIdeaIdRoute: typeof ReportIdeaIdRouteWithChildren
  IdeaIdeaIdAnalyzingRoute: typeof IdeaIdeaIdAnalyzingRoute
  IdeaIdeaIdStep1Route: typeof IdeaIdeaIdStep1Route
  IdeaIdeaIdStep2Route: typeof IdeaIdeaIdStep2Route
  IdeaIdeaIdStep3Route: typeof IdeaIdeaIdStep3Route
  IdeaIdeaIdStep4Route: typeof IdeaIdeaIdStep4Route
  IdeaIdeaIdStep5Route: typeof IdeaIdeaIdStep5Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$ideaId': {
      id: '/report/$ideaId'
      path: '/report/$ideaId'
      fullPath: '/report/$ideaId'
      preLoaderRoute: typeof ReportIdeaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idea/new': {
      id: '/idea/new'
      path: '/idea/new'
      fullPath: '/idea/new'
      preLoaderRoute: typeof IdeaNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$ideaId/print': {
      id: '/report/$ideaId/print'
      path: '/print'
      fullPath: '/report/$ideaId/print'
      preLoaderRoute: typeof ReportIdeaIdPrintRouteImport
      parentRoute: typeof ReportIdeaIdRoute
    }
    '/idea/$ideaId/step-5': {
      id: '/idea/$ideaId/step-5'
      path: '/idea/$ideaId/step-5'
      fullPath: '/idea/$ideaId/step-5'
      preLoaderRoute: typeof IdeaIdeaIdStep5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idea/$ideaId/step-4': {
      id: '/idea/$ideaId/step-4'
      path: '/idea/$ideaId/step-4'
      fullPath: '/idea/$ideaId/step-4'
      preLoaderRoute: typeof IdeaIdeaIdStep4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idea/$ideaId/step-3': {
      id: '/idea/$ideaId/step-3'
      path: '/idea/$ideaId/step-3'
      fullPath: '/idea/$ideaId/step-3'
      preLoaderRoute: typeof IdeaIdeaIdStep3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idea/$ideaId/step-2': {
      id: '/idea/$ideaId/step-2'
      path: '/idea/$ideaId/step-2'
      fullPath: '/idea/$ideaId/step-2'
      preLoaderRoute: typeof IdeaIdeaIdStep2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idea/$ideaId/step-1': {
      id: '/idea/$ideaId/step-1'
      path: '/idea/$ideaId/step-1'
      fullPath: '/idea/$ideaId/step-1'
      preLoaderRoute: typeof IdeaIdeaIdStep1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idea/$ideaId/analyzing': {
      id: '/idea/$ideaId/analyzing'
      path: '/idea/$ideaId/analyzing'
      fullPath: '/idea/$ideaId/analyzing'
      preLoaderRoute: typeof IdeaIdeaIdAnalyzingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReportIdeaIdRouteChildren {
  ReportIdeaIdPrintRoute: typeof ReportIdeaIdPrintRoute
}

const ReportIdeaIdRouteChildren: ReportIdeaIdRouteChildren = {
  ReportIdeaIdPrintRoute: ReportIdeaIdPrintRoute,
}

const ReportIdeaIdRouteWithChildren = ReportIdeaIdRoute._addFileChildren(
  ReportIdeaIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  IdeaNewRoute: IdeaNewRoute,
  ReportIdeaIdRoute: ReportIdeaIdRouteWithChildren,
  IdeaIdeaIdAnalyzingRoute: IdeaIdeaIdAnalyzingRoute,
  IdeaIdeaIdStep1Route: IdeaIdeaIdStep1Route,
  IdeaIdeaIdStep2Route: IdeaIdeaIdStep2Route,
  IdeaIdeaIdStep3Route: IdeaIdeaIdStep3Route,
  IdeaIdeaIdStep4Route: IdeaIdeaIdStep4Route,
  IdeaIdeaIdStep5Route: IdeaIdeaIdStep5Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
