/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedReportIdeaIdRouteImport } from './routes/_authed.report.$ideaId'
import { Route as AuthedIdeaNewRouteImport } from './routes/_authed.idea.new'
import { Route as AuthedReportIdeaIdPrintRouteImport } from './routes/_authed.report.$ideaId.print'
import { Route as AuthedIdeaIdeaIdStep5RouteImport } from './routes/_authed.idea.$ideaId.step-5'
import { Route as AuthedIdeaIdeaIdStep4RouteImport } from './routes/_authed.idea.$ideaId.step-4'
import { Route as AuthedIdeaIdeaIdStep3RouteImport } from './routes/_authed.idea.$ideaId.step-3'
import { Route as AuthedIdeaIdeaIdStep2RouteImport } from './routes/_authed.idea.$ideaId.step-2'
import { Route as AuthedIdeaIdeaIdStep1RouteImport } from './routes/_authed.idea.$ideaId.step-1'
import { Route as AuthedIdeaIdeaIdAnalyzingRouteImport } from './routes/_authed.idea.$ideaId.analyzing'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportIdeaIdRoute = AuthedReportIdeaIdRouteImport.update({
  id: '/report/$ideaId',
  path: '/report/$ideaId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIdeaNewRoute = AuthedIdeaNewRouteImport.update({
  id: '/idea/new',
  path: '/idea/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportIdeaIdPrintRoute = AuthedReportIdeaIdPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => AuthedReportIdeaIdRoute,
} as any)
const AuthedIdeaIdeaIdStep5Route = AuthedIdeaIdeaIdStep5RouteImport.update({
  id: '/idea/$ideaId/step-5',
  path: '/idea/$ideaId/step-5',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIdeaIdeaIdStep4Route = AuthedIdeaIdeaIdStep4RouteImport.update({
  id: '/idea/$ideaId/step-4',
  path: '/idea/$ideaId/step-4',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIdeaIdeaIdStep3Route = AuthedIdeaIdeaIdStep3RouteImport.update({
  id: '/idea/$ideaId/step-3',
  path: '/idea/$ideaId/step-3',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIdeaIdeaIdStep2Route = AuthedIdeaIdeaIdStep2RouteImport.update({
  id: '/idea/$ideaId/step-2',
  path: '/idea/$ideaId/step-2',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIdeaIdeaIdStep1Route = AuthedIdeaIdeaIdStep1RouteImport.update({
  id: '/idea/$ideaId/step-1',
  path: '/idea/$ideaId/step-1',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIdeaIdeaIdAnalyzingRoute =
  AuthedIdeaIdeaIdAnalyzingRouteImport.update({
    id: '/idea/$ideaId/analyzing',
    path: '/idea/$ideaId/analyzing',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/idea/new': typeof AuthedIdeaNewRoute
  '/report/$ideaId': typeof AuthedReportIdeaIdRouteWithChildren
  '/idea/$ideaId/analyzing': typeof AuthedIdeaIdeaIdAnalyzingRoute
  '/idea/$ideaId/step-1': typeof AuthedIdeaIdeaIdStep1Route
  '/idea/$ideaId/step-2': typeof AuthedIdeaIdeaIdStep2Route
  '/idea/$ideaId/step-3': typeof AuthedIdeaIdeaIdStep3Route
  '/idea/$ideaId/step-4': typeof AuthedIdeaIdeaIdStep4Route
  '/idea/$ideaId/step-5': typeof AuthedIdeaIdeaIdStep5Route
  '/report/$ideaId/print': typeof AuthedReportIdeaIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/idea/new': typeof AuthedIdeaNewRoute
  '/report/$ideaId': typeof AuthedReportIdeaIdRouteWithChildren
  '/idea/$ideaId/analyzing': typeof AuthedIdeaIdeaIdAnalyzingRoute
  '/idea/$ideaId/step-1': typeof AuthedIdeaIdeaIdStep1Route
  '/idea/$ideaId/step-2': typeof AuthedIdeaIdeaIdStep2Route
  '/idea/$ideaId/step-3': typeof AuthedIdeaIdeaIdStep3Route
  '/idea/$ideaId/step-4': typeof AuthedIdeaIdeaIdStep4Route
  '/idea/$ideaId/step-5': typeof AuthedIdeaIdeaIdStep5Route
  '/report/$ideaId/print': typeof AuthedReportIdeaIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/idea/new': typeof AuthedIdeaNewRoute
  '/_authed/report/$ideaId': typeof AuthedReportIdeaIdRouteWithChildren
  '/_authed/idea/$ideaId/analyzing': typeof AuthedIdeaIdeaIdAnalyzingRoute
  '/_authed/idea/$ideaId/step-1': typeof AuthedIdeaIdeaIdStep1Route
  '/_authed/idea/$ideaId/step-2': typeof AuthedIdeaIdeaIdStep2Route
  '/_authed/idea/$ideaId/step-3': typeof AuthedIdeaIdeaIdStep3Route
  '/_authed/idea/$ideaId/step-4': typeof AuthedIdeaIdeaIdStep4Route
  '/_authed/idea/$ideaId/step-5': typeof AuthedIdeaIdeaIdStep5Route
  '/_authed/report/$ideaId/print': typeof AuthedReportIdeaIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/idea/new'
    | '/report/$ideaId'
    | '/idea/$ideaId/analyzing'
    | '/idea/$ideaId/step-1'
    | '/idea/$ideaId/step-2'
    | '/idea/$ideaId/step-3'
    | '/idea/$ideaId/step-4'
    | '/idea/$ideaId/step-5'
    | '/report/$ideaId/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/idea/new'
    | '/report/$ideaId'
    | '/idea/$ideaId/analyzing'
    | '/idea/$ideaId/step-1'
    | '/idea/$ideaId/step-2'
    | '/idea/$ideaId/step-3'
    | '/idea/$ideaId/step-4'
    | '/idea/$ideaId/step-5'
    | '/report/$ideaId/print'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/dashboard'
    | '/_authed/idea/new'
    | '/_authed/report/$ideaId'
    | '/_authed/idea/$ideaId/analyzing'
    | '/_authed/idea/$ideaId/step-1'
    | '/_authed/idea/$ideaId/step-2'
    | '/_authed/idea/$ideaId/step-3'
    | '/_authed/idea/$ideaId/step-4'
    | '/_authed/idea/$ideaId/step-5'
    | '/_authed/report/$ideaId/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/report/$ideaId': {
      id: '/_authed/report/$ideaId'
      path: '/report/$ideaId'
      fullPath: '/report/$ideaId'
      preLoaderRoute: typeof AuthedReportIdeaIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/idea/new': {
      id: '/_authed/idea/new'
      path: '/idea/new'
      fullPath: '/idea/new'
      preLoaderRoute: typeof AuthedIdeaNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/report/$ideaId/print': {
      id: '/_authed/report/$ideaId/print'
      path: '/print'
      fullPath: '/report/$ideaId/print'
      preLoaderRoute: typeof AuthedReportIdeaIdPrintRouteImport
      parentRoute: typeof AuthedReportIdeaIdRoute
    }
    '/_authed/idea/$ideaId/step-5': {
      id: '/_authed/idea/$ideaId/step-5'
      path: '/idea/$ideaId/step-5'
      fullPath: '/idea/$ideaId/step-5'
      preLoaderRoute: typeof AuthedIdeaIdeaIdStep5RouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/idea/$ideaId/step-4': {
      id: '/_authed/idea/$ideaId/step-4'
      path: '/idea/$ideaId/step-4'
      fullPath: '/idea/$ideaId/step-4'
      preLoaderRoute: typeof AuthedIdeaIdeaIdStep4RouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/idea/$ideaId/step-3': {
      id: '/_authed/idea/$ideaId/step-3'
      path: '/idea/$ideaId/step-3'
      fullPath: '/idea/$ideaId/step-3'
      preLoaderRoute: typeof AuthedIdeaIdeaIdStep3RouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/idea/$ideaId/step-2': {
      id: '/_authed/idea/$ideaId/step-2'
      path: '/idea/$ideaId/step-2'
      fullPath: '/idea/$ideaId/step-2'
      preLoaderRoute: typeof AuthedIdeaIdeaIdStep2RouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/idea/$ideaId/step-1': {
      id: '/_authed/idea/$ideaId/step-1'
      path: '/idea/$ideaId/step-1'
      fullPath: '/idea/$ideaId/step-1'
      preLoaderRoute: typeof AuthedIdeaIdeaIdStep1RouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/idea/$ideaId/analyzing': {
      id: '/_authed/idea/$ideaId/analyzing'
      path: '/idea/$ideaId/analyzing'
      fullPath: '/idea/$ideaId/analyzing'
      preLoaderRoute: typeof AuthedIdeaIdeaIdAnalyzingRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedReportIdeaIdRouteChildren {
  AuthedReportIdeaIdPrintRoute: typeof AuthedReportIdeaIdPrintRoute
}

const AuthedReportIdeaIdRouteChildren: AuthedReportIdeaIdRouteChildren = {
  AuthedReportIdeaIdPrintRoute: AuthedReportIdeaIdPrintRoute,
}

const AuthedReportIdeaIdRouteWithChildren =
  AuthedReportIdeaIdRoute._addFileChildren(AuthedReportIdeaIdRouteChildren)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedIdeaNewRoute: typeof AuthedIdeaNewRoute
  AuthedReportIdeaIdRoute: typeof AuthedReportIdeaIdRouteWithChildren
  AuthedIdeaIdeaIdAnalyzingRoute: typeof AuthedIdeaIdeaIdAnalyzingRoute
  AuthedIdeaIdeaIdStep1Route: typeof AuthedIdeaIdeaIdStep1Route
  AuthedIdeaIdeaIdStep2Route: typeof AuthedIdeaIdeaIdStep2Route
  AuthedIdeaIdeaIdStep3Route: typeof AuthedIdeaIdeaIdStep3Route
  AuthedIdeaIdeaIdStep4Route: typeof AuthedIdeaIdeaIdStep4Route
  AuthedIdeaIdeaIdStep5Route: typeof AuthedIdeaIdeaIdStep5Route
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedIdeaNewRoute: AuthedIdeaNewRoute,
  AuthedReportIdeaIdRoute: AuthedReportIdeaIdRouteWithChildren,
  AuthedIdeaIdeaIdAnalyzingRoute: AuthedIdeaIdeaIdAnalyzingRoute,
  AuthedIdeaIdeaIdStep1Route: AuthedIdeaIdeaIdStep1Route,
  AuthedIdeaIdeaIdStep2Route: AuthedIdeaIdeaIdStep2Route,
  AuthedIdeaIdeaIdStep3Route: AuthedIdeaIdeaIdStep3Route,
  AuthedIdeaIdeaIdStep4Route: AuthedIdeaIdeaIdStep4Route,
  AuthedIdeaIdeaIdStep5Route: AuthedIdeaIdeaIdStep5Route,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
